### ISSUE TITLE
Add Difference (Increase in cases from the last hour / day )

### ISSUE THREAD

**Issue by himanshu2406** [himanshu2406/Corona-Tracker-Bot#2]
**Describe the solution you'd like**
Add the increase in cases / deaths , etc below the statistics for example: Cases: 100,000 (+1,000)

**Additional context**
To be added in [country](https://github.com/himanshu2406/Corona-Tracker-Bot/blob/b779a5f6801960f0f43710c70e6ceb957e8375c8/Bot/bot.py#L375) and [all](https://github.com/himanshu2406/Corona-Tracker-Bot/blob/b779a5f6801960f0f43710c70e6ceb957e8375c8/Bot/bot.py#L430)

**Comment by MaheshBharadwaj** [comment]
I think the line number in `to be added here` needs to be changed as it refers to an embed

**Comment by himanshu2406** [comment]
> I think the line number in `to be added here` needs to be changed as it refers to an embed

Done
